// Bookkeeping of reusable Three.js resources that must NOT be disposed when
// the board is rebuilt between snapshots. Anything not in these sets is
// assumed transient and disposed.

import * as THREE from "three";

import {
  boatCabinGeo,
  boatDeckGeo,
  boatHullGeo,
  boatJibGeo,
  boatMastGeo,
  boatSailGeo,
  cityBaseGeo,
  cityTopGeo,
  hexGeom,
  hexTopGeom,
  hexTransitionGeom,
  houseBaseGeo,
  houseRoofGeo,
  portCrateGeo,
  portPierGeo,
  portPostGeo,
  portQuayGeo,
  roadGeo,
  tokenGeom,
} from "../geometry";
import {
  foliageBlobGeo,
  foliageConeLargeGeo,
  foliageConeMedGeo,
  foliageConeSmallGeo,
  foliageConeTinyGeo,
  foliageCypressGeo,
  foliageRoundLargeGeo,
  foliageRoundMedGeo,
  foliageRoundSmallGeo,
  trunkSlimGeo,
  trunkStandardGeo,
  trunkStumpyGeo,
  trunkTallGeo,
  trunkThickGeo,
} from "../flora/trees";
import {
  foliageAutumnMat,
  foliageDeepMat,
  foliageLightMat,
  foliageMidMat,
  foliageOliveMat,
  foliagePineMat,
  foliageYellowMat,
  trunkBarkDarkMat,
  trunkBarkLightMat,
  trunkBarkMidMat,
  trunkBirchMat,
} from "../flora/trees";
import {
  boulderGeo,
  boulderSmallGeo,
  rockDarkMat,
  rockLightMat,
  rockMidMat,
  rockWarmMat,
  snowMat,
} from "../flora/mountains";
import {
  sheepBodyGeo,
  sheepEarGeo,
  sheepEyeGeo,
  sheepEyeMat,
  sheepFaceMat,
  sheepHeadGeo,
  sheepLegGeo,
  sheepWoolDarkMat,
  sheepWoolMat,
} from "../flora/pasture";
import {
  barnBodyGeo,
  barnDoorBraceGeo,
  barnDoorFrameSideGeo,
  barnDoorFrameTopGeo,
  barnDoorGeo,
  barnDoorMat,
  barnLoftFrameGeo,
  barnLoftWindowGeo,
  barnRedMat,
  barnRoofGeo,
  barnRoofMat,
  darkWindowMat,
  farmDarkWoodMat,
  farmWoodMat,
  hayBaleGeo,
  hayMat,
  hayStringGeo,
  hayStringMat,
  siloBodyGeo,
  siloBodyMat,
  siloCapGeo,
  siloDarkMat,
  siloDomeGeo,
  siloRibGeo,
  siloTubeGeo,
  siloTubeMat,
  siloTubeTopGeo,
  tractorBaseGeo,
  tractorBodyMat,
  tractorCabinGeo,
  tractorDarkGreyMat,
  tractorEngineGeo,
  tractorFrontRimGeo,
  tractorFrontTireGeo,
  tractorGlassMat,
  tractorPillarGeo,
  tractorPipeGeo,
  tractorRearRimGeo,
  tractorRearTireGeo,
  tractorRoofGeo,
  tractorTireMat,
  tractorTrimMat,
  troughBaseGeo,
  troughLongSideGeo,
  troughShortSideGeo,
  troughWaterGeo,
  troughWaterMat,
  wheatStalkGeo,
  wheatStalkMat,
  whiteTrimMat,
  windmillBaseGeo,
  windmillBladeGeo,
  windmillHeadGeo,
} from "../flora/farms";
import {
  brickGeo,
  brickMat,
  claySlabGeo,
  claySurfaceMat,
  clayHill1Mat,
  clayHill2Mat,
  craneArmGeo,
  craneBucketGeo,
  craneMastGeo,
  craneRopeGeo,
  craneSupportGeo,
  glowingFireMat,
  kilnArchGeo,
  kilnBaseGeo,
  kilnChimneyGeo,
  kilnDomeGeo,
  kilnFireGeo,
  mineBeamGeo,
  mineDarkMat,
  mineHoleGeo,
  minePostGeo,
  minecartBoxGeo,
  minecartLoadGeo,
  minecartLumpGeo,
  minecartRimGeo,
  minecartWheelGeo,
  pickaxeHandleGeo,
  pickaxeHeadGeo,
  quarryDarkStoneMat,
  quarryIronMat,
  quarryRopeMat,
  quarryStoneMat,
  quarryWoodMat,
  rubbleGeo,
  trackRailGeo,
  trackTieGeo,
} from "../flora/brickyards";
import { robberHighlightGeo } from "./highlights";
import {
  portBowTrimGeo,
  robberBaseGeo,
  robberBodyGeo,
  robberHeadGeo,
} from "./renderers";
import {
  boatCabinMat,
  boatFlagMat,
  boatHullMat,
  boatTrimMat,
  hexCapMat,
  hexSideMat,
  hexTopMaterials,
  hexTransitionMat,
  hlCityMat,
  hlRoadMat,
  hlRobberMat,
  hlRobberMatDim,
  hlSettlementMat,
  portCrateMat,
  portDarkWoodMat,
  portStoneMat,
  portWoodMat,
  sailMat,
} from "../materials";

export const reusableGeometries = new Set<THREE.BufferGeometry>([
  hexGeom,
  hexTopGeom,
  hexTransitionGeom,
  tokenGeom,
  roadGeo,
  houseBaseGeo,
  houseRoofGeo,
  cityBaseGeo,
  cityTopGeo,
  portQuayGeo,
  portPierGeo,
  portPostGeo,
  portCrateGeo,
  boatHullGeo,
  boatDeckGeo,
  boatCabinGeo,
  boatMastGeo,
  boatSailGeo,
  boatJibGeo,
  // Trees
  trunkSlimGeo,
  trunkStandardGeo,
  trunkThickGeo,
  trunkTallGeo,
  trunkStumpyGeo,
  foliageConeLargeGeo,
  foliageConeMedGeo,
  foliageConeSmallGeo,
  foliageConeTinyGeo,
  foliageCypressGeo,
  foliageRoundLargeGeo,
  foliageRoundMedGeo,
  foliageRoundSmallGeo,
  foliageBlobGeo,
  // Mountains (peak/snow-cap geos are per-instance, so only boulders reuse.)
  boulderGeo,
  boulderSmallGeo,
  // Pasture
  sheepBodyGeo,
  sheepHeadGeo,
  sheepEyeGeo,
  sheepEarGeo,
  sheepLegGeo,
  // Farm (wheat tile decoration)
  barnBodyGeo,
  barnRoofGeo,
  barnDoorGeo,
  barnDoorBraceGeo,
  barnDoorFrameTopGeo,
  barnDoorFrameSideGeo,
  barnLoftFrameGeo,
  barnLoftWindowGeo,
  siloBodyGeo,
  siloRibGeo,
  siloDomeGeo,
  siloCapGeo,
  siloTubeGeo,
  siloTubeTopGeo,
  windmillBaseGeo,
  windmillHeadGeo,
  windmillBladeGeo,
  hayBaleGeo,
  hayStringGeo,
  troughBaseGeo,
  troughLongSideGeo,
  troughShortSideGeo,
  troughWaterGeo,
  wheatStalkGeo,
  // Tractor
  tractorBaseGeo,
  tractorEngineGeo,
  tractorPipeGeo,
  tractorCabinGeo,
  tractorPillarGeo,
  tractorRoofGeo,
  tractorRearTireGeo,
  tractorRearRimGeo,
  tractorFrontTireGeo,
  tractorFrontRimGeo,
  // Brickyard (brick tile decoration)
  claySlabGeo,
  mineHoleGeo,
  minePostGeo,
  mineBeamGeo,
  rubbleGeo,
  pickaxeHandleGeo,
  pickaxeHeadGeo,
  craneMastGeo,
  craneArmGeo,
  craneRopeGeo,
  craneBucketGeo,
  craneSupportGeo,
  kilnBaseGeo,
  kilnDomeGeo,
  kilnChimneyGeo,
  kilnArchGeo,
  kilnFireGeo,
  brickGeo,
  trackRailGeo,
  trackTieGeo,
  minecartBoxGeo,
  minecartRimGeo,
  minecartLoadGeo,
  minecartLumpGeo,
  minecartWheelGeo,
  // Hoisted per-rebuild geos (robber + port bow trim + robber-move highlight)
  robberBaseGeo,
  robberBodyGeo,
  robberHeadGeo,
  portBowTrimGeo,
  robberHighlightGeo,
]);

export const reusableMaterials = new Set<THREE.Material>([
  hexSideMat,
  hexCapMat,
  ...Object.values(hexTopMaterials),
  hexTransitionMat,
  portWoodMat,
  portDarkWoodMat,
  portStoneMat,
  portCrateMat,
  boatHullMat,
  boatTrimMat,
  boatCabinMat,
  boatFlagMat,
  sailMat,
  // Trees
  trunkBarkDarkMat,
  trunkBarkMidMat,
  trunkBarkLightMat,
  trunkBirchMat,
  foliageDeepMat,
  foliagePineMat,
  foliageMidMat,
  foliageLightMat,
  foliageOliveMat,
  foliageAutumnMat,
  foliageYellowMat,
  // Mountains
  rockDarkMat,
  rockMidMat,
  rockLightMat,
  rockWarmMat,
  snowMat,
  // Pasture
  sheepWoolMat,
  sheepWoolDarkMat,
  sheepFaceMat,
  sheepEyeMat,
  // Farm (wheat tile decoration)
  barnRedMat,
  barnRoofMat,
  barnDoorMat,
  whiteTrimMat,
  darkWindowMat,
  siloBodyMat,
  siloDarkMat,
  siloTubeMat,
  farmWoodMat,
  farmDarkWoodMat,
  hayMat,
  hayStringMat,
  wheatStalkMat,
  troughWaterMat,
  // Tractor
  tractorBodyMat,
  tractorTrimMat,
  tractorTireMat,
  tractorGlassMat,
  tractorDarkGreyMat,
  // Brickyard (brick tile decoration)
  claySurfaceMat,
  clayHill1Mat,
  clayHill2Mat,
  brickMat,
  quarryWoodMat,
  quarryStoneMat,
  quarryDarkStoneMat,
  quarryIronMat,
  quarryRopeMat,
  glowingFireMat,
  mineDarkMat,
  // Highlights
  hlSettlementMat,
  hlRoadMat,
  hlCityMat,
  hlRobberMat,
  hlRobberMatDim,
]);
